### ISSUE TITLE
Error on using ini_setting

### ISSUE THREAD

**Issue by jcrawfordor** [voxpupuli/puppet-splunk#77] opened 2016-12-08 23:28 UTC
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.5.3
- Distribution: RHEL7
- Module version: 5.0.2

## How to reproduce (e.g Puppet code you use)

```
  class { '::splunk::params':
    server => 'splunkmaster.domain.name'
  }

  class { '::splunk::forwarder':
    pkg_provider => 'yum',
    package_name => 'splunkforwarder',
    package_ensure => installed
  }
```

## What are you seeing

> Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Error while evaluating a Resource Statement, Could not autoload puppet/type/splunk_config: Could not autoload puppet/provider/splunk_distsearch/ini_setting: undefined method `provider' for nil:NilClass at /etc/puppetlabs/code/environments/splunk_client/modules/splunk/manifests/params.pp:244:3 on node i-26932f02

## What behaviour did you expect instead

Installation of Splunk forwarder

## Any additional information you'd like to impart

I'm having a hard time telling from the documentation exactly how to use this module in a scenario where the package is in a local yum repository rather than served by the puppetmaster, but I've tried to work it out from the source code. I'm not clear on why I'm getting this particular error though.

**Comment by ccjoelm** [comment] 2017-02-01 04:54
I'm having the same issue.  Did you ever figure out how to work around this or what the cause was?

Thanks..Joel

**Comment by jcrawfordor** [comment] 2017-02-02 16:07
Ultimately I didn't find a workaround, our requirements changed a bit and I ended up configuring Puppet manually. I did make heavy use of ini_setting in that process though without trouble.

**Comment by TraGicCode** [comment] 2017-10-09 04:24
@jcrawfordor @ccjoelm I'm unable to reproduce this with the lastest version of the module.  I'm going to close this and if you can reproduce it i can investigate this more.

**Closed by TraGicCode** 2017-10-09 04:24 UTC
Labels: bug

**Comment by belfast77** [comment] 2018-01-23 09:14
@jcrawfordor @ccjoelm I initially got a similar error as above, because I forgot to add the module dependencies.
"name": "puppetlabs-inifile",
"version_requirement": ">= 1.4.1 < 2.0.0"
and 
"name": "puppet-archive",
"version_requirement": ">= 2.0.0 < 3.0.0"
